/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/porsche.glb --types --keepnames --shadows --root public --output src/components/R3F/Models/Porsche.tsx 
*/

import type * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh
    boot011: THREE.Mesh
    boot010: THREE.Mesh
    boot009: THREE.Mesh
    boot008: THREE.Mesh
    Plane006: THREE.Mesh
    Plane005: THREE.Mesh
    boot007: THREE.Mesh
    window_rear001: THREE.Mesh
    boot006: THREE.Mesh
    boot005: THREE.Mesh
    boot004: THREE.Mesh
    boot003: THREE.Mesh
    rearLight: THREE.Mesh
    boot002: THREE.Mesh
    boot001: THREE.Mesh
    Mesh_9: THREE.Mesh
    Mesh_10: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
    Plane004_3: THREE.Mesh
    bumper_front009: THREE.Mesh
    headLight: THREE.Mesh
    Plane014: THREE.Mesh
    Plane014_1: THREE.Mesh
    Plane014_2: THREE.Mesh
    Cube001: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder008_1: THREE.Mesh
    Cylinder008_2: THREE.Mesh
    Cylinder008_3: THREE.Mesh
    underbody: THREE.Mesh
    boot: THREE.Mesh
    Plane004: THREE.Mesh
    Plane003: THREE.Mesh
    Plane002: THREE.Mesh
    Plane008: THREE.Mesh
    Plane008_1: THREE.Mesh
    Mesh_13: THREE.Mesh
    Mesh_14: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder004_2: THREE.Mesh
    Cylinder004_3: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder005_2: THREE.Mesh
    Cylinder005_3: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder006_1: THREE.Mesh
    Cylinder006_2: THREE.Mesh
    Cylinder006_3: THREE.Mesh
    boot012: THREE.Mesh
  }
  materials: {
    full_black: THREE.MeshStandardMaterial
    coat: THREE.MeshStandardMaterial
    plastic: THREE.MeshStandardMaterial
    silver: THREE.MeshStandardMaterial
    paint: THREE.MeshStandardMaterial
    license: THREE.MeshStandardMaterial
    logo: THREE.MeshStandardMaterial
    window: THREE.MeshStandardMaterial
    tex_shiny: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    lights: THREE.MeshStandardMaterial
    rubber: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Porsche(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/porsche.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials.full_black} scale={[0.332, 0.318, 0.318]} />
      <mesh name="boot011" castShadow receiveShadow geometry={nodes.boot011.geometry} material={materials.coat} />
      <mesh name="boot010" castShadow receiveShadow geometry={nodes.boot010.geometry} material={materials.plastic} />
      <mesh name="boot009" castShadow receiveShadow geometry={nodes.boot009.geometry} material={materials.silver} />
      <mesh name="boot008" castShadow receiveShadow geometry={nodes.boot008.geometry} material={materials.paint} />
      <mesh name="Plane006" castShadow receiveShadow geometry={nodes.Plane006.geometry} material={materials.license} position={[0, -0.432, 3.75]} rotation={[-3.06, 0, Math.PI]} scale={[0.395, 0.357, 0.395]} />
      <mesh name="Plane005" castShadow receiveShadow geometry={nodes.Plane005.geometry} material={materials.license} position={[0, -0.292, -3.704]} rotation={[0.114, 0, 0]} scale={[0.393, 0.356, 0.393]} />
      <mesh name="boot007" castShadow receiveShadow geometry={nodes.boot007.geometry} material={materials.logo} />
      <mesh name="window_rear001" castShadow receiveShadow geometry={nodes.window_rear001.geometry} material={materials.full_black} />
      <mesh name="boot006" castShadow receiveShadow geometry={nodes.boot006.geometry} material={materials.full_black} />
      <mesh name="boot005" castShadow receiveShadow geometry={nodes.boot005.geometry} material={materials.paint} />
      <mesh name="boot004" castShadow receiveShadow geometry={nodes.boot004.geometry} material={materials.window} />
      <mesh name="boot003" castShadow receiveShadow geometry={nodes.boot003.geometry} material={materials.tex_shiny} position={[0, 0, -0.003]} />
      <mesh name="rearLight" castShadow receiveShadow geometry={nodes.rearLight.geometry} material={materials.tex_shiny} position={[0.005, 0.107, -3.581]} />
      <mesh name="boot002" castShadow receiveShadow geometry={nodes.boot002.geometry} material={materials.paint} />
      <mesh name="boot001" castShadow receiveShadow geometry={nodes.boot001.geometry} material={materials.paint} />
      <mesh name="bumper_front009" castShadow receiveShadow geometry={nodes.bumper_front009.geometry} material={materials.tex_shiny} />
      <mesh name="headLight" castShadow receiveShadow geometry={nodes.headLight.geometry} material={materials.glass} rotation={[-0.006, 0, 0]} scale={1.036} />
      <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials.plastic} position={[0.036, 0.333, 1.56]} rotation={[0.727, -0.244, 0.073]} scale={[0.014, 0.012, 0.014]} />
      <group name="tire_backRight" position={[-1.336, -0.51, -2.122]}>
        <mesh name="Cylinder008" castShadow receiveShadow geometry={nodes.Cylinder008.geometry} material={materials.silver} />
        <mesh name="Cylinder008_1" castShadow receiveShadow geometry={nodes.Cylinder008_1.geometry} material={materials.plastic} />
        <mesh name="Cylinder008_2" castShadow receiveShadow geometry={nodes.Cylinder008_2.geometry} material={materials.rubber} />
        <mesh name="Cylinder008_3" castShadow receiveShadow geometry={nodes.Cylinder008_3.geometry} material={materials['Material.001']} />
      </group>
      <mesh name="underbody" castShadow receiveShadow geometry={nodes.underbody.geometry} material={materials.full_black} />
      <mesh name="boot" castShadow receiveShadow geometry={nodes.boot.geometry} material={materials.full_black} />
      <mesh name="Plane004" castShadow receiveShadow geometry={nodes.Plane004.geometry} material={materials.paint} position={[-0.488, -0.328, -3.684]} rotation={[-1.461, 0.802, 0.064]} scale={0.059} />
      <mesh name="Plane003" castShadow receiveShadow geometry={nodes.Plane003.geometry} material={materials.paint} position={[0.436, -0.117, -3.723]} rotation={[-1.375, 0.797, -0.151]} scale={0.024} />
      <mesh name="Plane002" castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials.paint} position={[-1.053, -0.126, -3.51]} rotation={[-1.957, 0.606, 0.785]} scale={0.024} />
      <group name="windshield" position={[0, 0.007, 0.003]}>
        <mesh name="Plane008" castShadow receiveShadow geometry={nodes.Plane008.geometry} material={materials.window} />
        <mesh name="Plane008_1" castShadow receiveShadow geometry={nodes.Plane008_1.geometry} material={materials.plastic} />
      </group>
      <group name="tire_backLeft" position={[1.336, -0.51, -2.122]}>
        <mesh name="Cylinder004" castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials.silver} />
        <mesh name="Cylinder004_1" castShadow receiveShadow geometry={nodes.Cylinder004_1.geometry} material={materials.plastic} />
        <mesh name="Cylinder004_2" castShadow receiveShadow geometry={nodes.Cylinder004_2.geometry} material={materials.rubber} />
        <mesh name="Cylinder004_3" castShadow receiveShadow geometry={nodes.Cylinder004_3.geometry} material={materials['Material.001']} />
      </group>
      <group name="tire_frontRight" position={[-1.336, -0.51, 2.096]}>
        <mesh name="Cylinder005" castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={materials.silver} />
        <mesh name="Cylinder005_1" castShadow receiveShadow geometry={nodes.Cylinder005_1.geometry} material={materials.plastic} />
        <mesh name="Cylinder005_2" castShadow receiveShadow geometry={nodes.Cylinder005_2.geometry} material={materials.rubber} />
        <mesh name="Cylinder005_3" castShadow receiveShadow geometry={nodes.Cylinder005_3.geometry} material={materials['Material.001']} />
      </group>
      <group name="tire_frontLeft" position={[1.336, -0.51, 2.096]}>
        <mesh name="Cylinder006" castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={materials.silver} />
        <mesh name="Cylinder006_1" castShadow receiveShadow geometry={nodes.Cylinder006_1.geometry} material={materials.plastic} />
        <mesh name="Cylinder006_2" castShadow receiveShadow geometry={nodes.Cylinder006_2.geometry} material={materials.rubber} />
        <mesh name="Cylinder006_3" castShadow receiveShadow geometry={nodes.Cylinder006_3.geometry} material={materials['Material.001']} />
      </group>
      <mesh name="boot012" castShadow receiveShadow geometry={nodes.boot012.geometry} material={materials.silver} position={[0, -0.645, -3.626]} />
      <mesh name="Mesh_9" castShadow receiveShadow geometry={nodes.Mesh_9.geometry} material={materials.plastic} />
      <mesh name="Mesh_10" castShadow receiveShadow geometry={nodes.Mesh_10.geometry} material={materials.glass} />
      <mesh name="Plane004_1" castShadow receiveShadow geometry={nodes.Plane004_1.geometry} material={materials.plastic} />
      <mesh name="Plane004_2" castShadow receiveShadow geometry={nodes.Plane004_2.geometry} material={materials.silver} />
      <mesh name="Plane004_3" castShadow receiveShadow geometry={nodes.Plane004_3.geometry} material={materials.lights} />
      <mesh name="Plane014" castShadow receiveShadow geometry={nodes.Plane014.geometry} material={materials.silver} />
      <mesh name="Plane014_1" castShadow receiveShadow geometry={nodes.Plane014_1.geometry} material={materials.lights} />
      <mesh name="Plane014_2" castShadow receiveShadow geometry={nodes.Plane014_2.geometry} material={materials.plastic} />
      {/* <mesh name="Mesh_13" castShadow receiveShadow geometry={nodes.Mesh_13.geometry} material={materials.window} /> */}
      <mesh name="Mesh_14" castShadow receiveShadow geometry={nodes.Mesh_14.geometry} material={materials.window} />
    </group>
  )
}

useGLTF.preload('/models/porsche.glb')
